name: Update GEE Links

on:
  schedule:
    - cron: '0 */10 * * *'  # Каждые 10 часов (UTC)
  workflow_dispatch:         # Для ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30      # Лимит выполнения

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade google-auth-oauthlib
      
      - name: Set up GEE credentials
        run: |
          mkdir -p ~/.config/earthengine/
          echo '${{ secrets.GEE_CREDENTIALS }}' > ~/.config/earthengine/credentials.json
      
      - name: Run script
        run: python main.py
        env:
          G_SHEETS_KEY: ${{ secrets.G_SHEETS_KEY }}
