- name: Debug
  run: |
    echo "Проверка доступа к таблице..."
    python -c "
    import gspread
    from oauth2client.service_account import ServiceAccountCredentials
    creds = ${{ secrets.GEE_CREDENTIALS }}
    scope = ['https://www.googleapis.com/auth/spreadsheets']
    client = gspread.authorize(ServiceAccountCredentials.from_json_keyfile_dict(creds, scope))
    sheet = client.open_by_key('1oz12JnCKuM05PpHNR1gkNR_tPENazabwOGkWWeAc2hY')
    print(f'Успешный доступ к таблице: {sheet.title}')
    "
name: GEE Script Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install earthengine-api gspread oauth2client

    - name: Authenticate GEE
      run: |
        echo "${{ secrets.GEE_CREDENTIALS }}" > service_account.json
        python -c "
        import ee
        ee.Authenticate(service_account='service_account.json')
        print('✅ Аутентификация GEE выполнена')
        "

    - name: Run Main Script
      run: python main.py
      env:
        GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
        
