name: GEE Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install earthengine-api gspread oauth2client

    - name: Authenticate Earth Engine
      run: |
        echo "${{ secrets.GEE_CREDENTIALS }}" > service_account.json
        python -c "
        import ee
        ee.Authenticate(service_account='service_account.json')
        print('✅ Earth Engine authenticated')
        "

    - name: Verify Google Sheets Access
      run: |
        python -c "
        import gspread
        from oauth2client.service_account import ServiceAccountCredentials
        creds = ${{ secrets.GEE_CREDENTIALS }}
        scope = ['https://www.googleapis.com/auth/spreadsheets']
        client = gspread.authorize(ServiceAccountCredentials.from_json_keyfile_dict(creds, scope))
        print('✅ Google Sheets access verified')
        "

    - name: Run Main Script
      run: python main.py
      env:
        GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
