name: Update GEE Links

on:
  schedule:
    - cron: '0 */10 * * *'  # Каждые 10 часов (UTC)
  workflow_dispatch:  # Для ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Лимит выполнения
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gspread oauth2client
      
      - name: Authenticate GEE
        run: |
          python -c "import ee; ee.Initialize()" || true
        env:
          GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
      
      - name: Run script
        run: python main.py
        env:
          G_SHEETS_KEY: ${{ secrets.G_SHEETS_KEY }}
          GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
