name: Update GEE Links

on:
  schedule:
    - cron: '0 */10 * * *'  # Каждые 10 часов
  workflow_dispatch:  # Для ручного запуска

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -c "import ee; ee.Authenticate()" || true
      
      - name: Run script
        run: python main.py
        env:
          GEE_CREDENTIALS: ${{ secrets.GEE_CREDENTIALS }}
